In [1]:
import os
import pandas as pd
import numpy as np

In [ ]:
Dataset source: https://www.kaggle.com/datasets/sandhyapeesara/cloud-anomaly-data

SyntaxError: invalid syntax (1401395098.py, line 1)

In [3]:
path='../data/dataset/Cloud_Anomaly_Dataset.csv'

In [4]:
data=pd.read_csv(path)
print(data)

                                       vm_id         timestamp  cpu_usage  \
0       c5215826-6237-4a33-9312-72c1df909881  25-01-2023 09:10  54.881350
1       29690bc6-1f34-403b-b509-a1ecb1834fb8  26-01-2023 04:46  71.518937
2       2e55abc3-5bad-46cb-b445-a577f5e9bf2a  13-01-2023 23:39        NaN
3       ea8455b0-251c-4470-b7ea-8d40476e3434  14-01-2023 19:59  79.172504
4       fd28310b-be6f-4320-a664-de02274993d9  18-01-2023 11:22  87.001215
...                                      ...               ...        ...
277565  c5334ec8-d0c7-4c7d-ad45-1550bcb87446  31-01-2023 19:28  83.918513
277566  9bce6162-acea-4e26-9d9e-7a24c9c60b71  11-01-2023 18:24  12.172667
277567  dc6bbd4b-f660-4085-917f-a8b8e84d1447  14-01-2023 20:35  63.527355
277568  de72031d-ef09-4d5f-8730-99f068338490  22-01-2023 21:36  43.256174
277569  89b1f28f-6134-4ba5-8e9f-8777ba43887a  07-01-2023 14:02  49.187027

        memory_usage  network_traffic  power_consumption  \
0          78.950861       164.775973         287.808986
1          29.901883              NaN         362.273569
2          92.709195       203.674847         231.467903
3           2.972252       926.374030         173.559325
4          46.620176       437.188115          77.054702
...              ...              ...                ...
277565     85.606782       545.610846         369.996273
277566     78.222272        72.425667                NaN
277567     36.998653       407.818069          14.016786
277568     50.937723       538.460617         280.242122
277569     37.051783        65.609313         124.150466

        num_executed_instructions  execution_time  energy_efficiency  \
0                          7527.0       69.345575           0.553589
1                          5348.0       41.396040           0.349856
2                          5483.0       24.602549           0.796277
3                          8644.0       55.702673           0.779499
4                          9427.0             NaN           0.207164
...                           ...             ...                ...
277565                     6861.0       15.292729           0.157451
277566                     1604.0       82.430493                NaN
277567                     9292.0       21.464536           0.247330
277568                     9183.0       78.145239           0.308062
277569                     1013.0        0.546173           0.380156

       task_type task_priority task_status  Anomaly status
0        network        medium     waiting               0
1             io          high   completed               0
2             io        medium   completed               0
3        compute        medium   completed               0
4            NaN           low     waiting               0
...          ...           ...         ...             ...
277565   compute        medium     running               0
277566       NaN          high     running               0
277567   network        medium     waiting               0
277568        io        medium     waiting               0
277569       NaN        medium     running               0

[277570 rows x 13 columns]

In [5]:
clean_data=data.dropna()
clean_data = clean_data[clean_data["cpu_usage"] >= 5]
clean_data = clean_data[clean_data["memory_usage"] >= 5]
print(clean_data)

                                       vm_id         timestamp  cpu_usage  \
0       c5215826-6237-4a33-9312-72c1df909881  25-01-2023 09:10  54.881350
7       aaa03097-d35c-44cc-af28-08ac4a8ac005  15-01-2023 21:12  67.063787
10      e498a339-3f0f-4e72-b979-69dc40010f20  01-01-2023 11:30   9.609841
15      ddbd9bc0-df49-4c6f-800d-f24e5eae6160  27-01-2023 21:53  82.894003
16      57f1377e-0fb3-424b-ab60-a0dd2a26050d  10-01-2023 11:22  24.875314
...                                      ...               ...        ...
277556  e85213ba-c282-458d-a1a5-7926d2915819  05-01-2023 16:36  72.788804
277564  6a292798-5a79-4772-975f-b944bc42e25e  26-01-2023 21:30  72.132164
277565  c5334ec8-d0c7-4c7d-ad45-1550bcb87446  31-01-2023 19:28  83.918513
277567  dc6bbd4b-f660-4085-917f-a8b8e84d1447  14-01-2023 20:35  63.527355
277568  de72031d-ef09-4d5f-8730-99f068338490  22-01-2023 21:36  43.256174

        memory_usage  network_traffic  power_consumption  \
0          78.950861       164.775973         287.808986
7          56.200805       856.372924         300.816338
10          5.842704       195.366922         153.257058
15         87.019231       542.554835         178.856362
16         69.984631       668.823780         346.472355
...              ...              ...                ...
277556     78.995342       413.184462         445.832912
277564      5.345731       717.907379         152.142318
277565     85.606782       545.610846         369.996273
277567     36.998653       407.818069          14.016786
277568     50.937723       538.460617         280.242122

        num_executed_instructions  execution_time  energy_efficiency  \
0                          7527.0       69.345575           0.553589
7                          3925.0        1.625046           0.979356
10                         2617.0       99.876272           0.458982
15                           25.0       77.960196           0.519331
16                         6927.0       10.614161           0.651735
...                           ...             ...                ...
277556                     7354.0       33.995004           0.289033
277564                     2939.0       90.577668           0.925345
277565                     6861.0       15.292729           0.157451
277567                     9292.0       21.464536           0.247330
277568                     9183.0       78.145239           0.308062

       task_type task_priority task_status  Anomaly status
0        network        medium     waiting               0
7             io          high     running               0
10       network           low     waiting               0
15            io           low     running               0
16            io          high   completed               0
...          ...           ...         ...             ...
277556   network        medium     running               0
277564   network           low   completed               0
277565   compute        medium     running               0
277567   network        medium     waiting               0
277568        io        medium     waiting               0

[78387 rows x 13 columns]

In [6]:
#x.x.x.0 & x.x.x.255 skip cuz net and boardcast address
def assign_IP(n):
    ips = []

    a, b, c, d = 10, 0, 0, 1
    for i in range(n):
        if(d==256):
            d=1
            c=c+1
            if(c==256):
                c=0
                b=b+1
                if(b==256):
                    b=0
                    a=a+1
                    if(a==256):
                        if(a==b==c==d==255):
                            print(f"out of IP address. Stop at {i} rows")
                            break
        ips.append(f"{a}.{b}.{c}.{d}")
        d=d+1
    return ips

In [7]:
#clean_data.drop(["ip"], axis=1, inplace=True)

In [8]:
print(clean_data)

                                       vm_id         timestamp  cpu_usage  \
0       c5215826-6237-4a33-9312-72c1df909881  25-01-2023 09:10  54.881350
7       aaa03097-d35c-44cc-af28-08ac4a8ac005  15-01-2023 21:12  67.063787
10      e498a339-3f0f-4e72-b979-69dc40010f20  01-01-2023 11:30   9.609841
15      ddbd9bc0-df49-4c6f-800d-f24e5eae6160  27-01-2023 21:53  82.894003
16      57f1377e-0fb3-424b-ab60-a0dd2a26050d  10-01-2023 11:22  24.875314
...                                      ...               ...        ...
277556  e85213ba-c282-458d-a1a5-7926d2915819  05-01-2023 16:36  72.788804
277564  6a292798-5a79-4772-975f-b944bc42e25e  26-01-2023 21:30  72.132164
277565  c5334ec8-d0c7-4c7d-ad45-1550bcb87446  31-01-2023 19:28  83.918513
277567  dc6bbd4b-f660-4085-917f-a8b8e84d1447  14-01-2023 20:35  63.527355
277568  de72031d-ef09-4d5f-8730-99f068338490  22-01-2023 21:36  43.256174

        memory_usage  network_traffic  power_consumption  \
0          78.950861       164.775973         287.808986
7          56.200805       856.372924         300.816338
10          5.842704       195.366922         153.257058
15         87.019231       542.554835         178.856362
16         69.984631       668.823780         346.472355
...              ...              ...                ...
277556     78.995342       413.184462         445.832912
277564      5.345731       717.907379         152.142318
277565     85.606782       545.610846         369.996273
277567     36.998653       407.818069          14.016786
277568     50.937723       538.460617         280.242122

        num_executed_instructions  execution_time  energy_efficiency  \
0                          7527.0       69.345575           0.553589
7                          3925.0        1.625046           0.979356
10                         2617.0       99.876272           0.458982
15                           25.0       77.960196           0.519331
16                         6927.0       10.614161           0.651735
...                           ...             ...                ...
277556                     7354.0       33.995004           0.289033
277564                     2939.0       90.577668           0.925345
277565                     6861.0       15.292729           0.157451
277567                     9292.0       21.464536           0.247330
277568                     9183.0       78.145239           0.308062

       task_type task_priority task_status  Anomaly status
0        network        medium     waiting               0
7             io          high     running               0
10       network           low     waiting               0
15            io           low     running               0
16            io          high   completed               0
...          ...           ...         ...             ...
277556   network        medium     running               0
277564   network           low   completed               0
277565   compute        medium     running               0
277567   network        medium     waiting               0
277568        io        medium     waiting               0

[78387 rows x 13 columns]

In [9]:
ips = assign_IP(len(clean_data))
clean_data.insert(1, "ip", ips)

In [10]:
clean_data.tail()

,vm_id,ip,timestamp,cpu_usage,memory_usage,network_traffic,power_consumption,num_executed_instructions,execution_time,energy_efficiency,task_type,task_priority,task_status,Anomaly status
277556,e85213ba-c282-458d-a1a5-7926d2915819,10.1.51.98,05-01-2023 16:36,72.788804,78.995342,413.184462,445.832912,7354.0,33.995004,0.289033,network,medium,running,0
277564,6a292798-5a79-4772-975f-b944bc42e25e,10.1.51.99,26-01-2023 21:30,72.132164,5.345731,717.907379,152.142318,2939.0,90.577668,0.925345,network,low,completed,0
277565,c5334ec8-d0c7-4c7d-ad45-1550bcb87446,10.1.51.100,31-01-2023 19:28,83.918513,85.606782,545.610846,369.996273,6861.0,15.292729,0.157451,compute,medium,running,0
277567,dc6bbd4b-f660-4085-917f-a8b8e84d1447,10.1.51.101,14-01-2023 20:35,63.527355,36.998653,407.818069,14.016786,9292.0,21.464536,0.247330,network,medium,waiting,0
277568,de72031d-ef09-4d5f-8730-99f068338490,10.1.51.102,22-01-2023 21:36,43.256174,50.937723,538.460617,280.242122,9183.0,78.145239,0.308062,io,medium,waiting,0

In [11]:
final_data=clean_data.drop(["vm_id","timestamp","power_consumption","num_executed_instructions","energy_efficiency","task_type","task_priority","task_status","Anomaly status"], axis=1)

In [12]:
print(final_data)

                 ip  cpu_usage  memory_usage  network_traffic  execution_time
0          10.0.0.1  54.881350     78.950861       164.775973       69.345575
7          10.0.0.2  67.063787     56.200805       856.372924        1.625046
10         10.0.0.3   9.609841      5.842704       195.366922       99.876272
15         10.0.0.4  82.894003     87.019231       542.554835       77.960196
16         10.0.0.5  24.875314     69.984631       668.823780       10.614161
...             ...        ...           ...              ...             ...
277556   10.1.51.98  72.788804     78.995342       413.184462       33.995004
277564   10.1.51.99  72.132164      5.345731       717.907379       90.577668
277565  10.1.51.100  83.918513     85.606782       545.610846       15.292729
277567  10.1.51.101  63.527355     36.998653       407.818069       21.464536
277568  10.1.51.102  43.256174     50.937723       538.460617       78.145239

[78387 rows x 5 columns]

In [13]:
latency=(
    (clean_data["execution_time"]/100) *
    ((clean_data["cpu_usage"] + clean_data["memory_usage"]) /200) *  clean_data["network_traffic"]
)
print(latency)

0          76.461585
7           8.577030
10         15.075904
15        359.346791
16         33.670552
             ...
277556    106.599581
277564    251.905339
277565     70.724924
277567     43.998351
277568    198.175169
Length: 78387, dtype: float64

In [14]:
final_data.insert(len(final_data.columns),"latency",latency)
final_data[["latency", "cpu_usage", "memory_usage"]] =final_data[["latency", "cpu_usage", "memory_usage"]].round(2)
final_data[["network_traffic","execution_time"]] =final_data[["network_traffic", "execution_time"]].round(0)

In [15]:
final_data.head()

,ip,cpu_usage,memory_usage,network_traffic,execution_time,latency
0,10.0.0.1,54.88,78.95,165.0,69.0,76.46
7,10.0.0.2,67.06,56.20,856.0,2.0,8.58
10,10.0.0.3,9.61,5.84,195.0,100.0,15.08
15,10.0.0.4,82.89,87.02,543.0,78.0,359.35
16,10.0.0.5,24.88,69.98,669.0,11.0,33.67

In [16]:
final_data.to_csv("dataset.csv", index=False, encoding="utf-8")

In [17]:
!n

'n' is not recognized as an internal or external command,
operable program or batch file.

In [18]:
import os
import random

random.seed(42)
n_cases = 100
output_dir = "../data/examples"
os.makedirs(output_dir, exist_ok=True)

for i in range(1, n_cases + 1):

    n_rows = random.randint(2, 3)

    case_df = final_data.sample( n=n_rows, replace=False)

    case_df.to_csv(
        os.path.join(output_dir, f"case_{i}.csv"),
        index=False
    )

print(f"Created {n_cases} test cases in {output_dir}")

Created 100 test cases in ../data/examples